---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insights
  namespace: shop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insights
  template:
    metadata:
      labels:
        app: redis-insights
    spec:
      containers:
        - name: redis-insights
          image: redislabs/redisinsight:2.70.1
          ports:
            - containerPort: 5540
          env:
            - name: RI_REDIS_HOSTS
              value: "redis"
