apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: prod-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/adisoncavani/shop-microservices/order-service:0.0.7
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-shared
            - secretRef:
                name: shared-secrets
            - secretRef:
                name: order-service
          env:
            - name: OTEL_SERVICE_NAME
              value: order-service
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.name=$(K8S_POD_NAME)"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
