apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: prod-shop
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/(health|alive|api/health) {
        return 404 '';
      }
spec:
  ingressClassName: nginx
  rules:
    - host: api-shop.k1ng.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 80
  tls:
    - hosts:
        - api-shop.k1ng.dev
      secretName: api-tls
