apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: prod-shop
spec:
  type: ClusterIP
  selector:
    app: seq
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: ingest
      port: 5341
      targetPort: 5341
